name: .NET CI/CD

on:
  pull_request:
    branches: ["develop"]
  # pull_request:
  #   branches: ["main"]

permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create dummy local.settings.json
        run: echo "{}" > api/local.settings.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./tests/Api.Tests.csproj

      - name: Build
        run: dotnet build ./tests/Api.Tests.csproj --no-restore

      - name: Run tests
        run: dotnet test ./tests/Api.Tests.csproj --no-build --verbosity normal
